name: quiz_generator_pro
description: "A professional AI-powered Quiz Generator app built with Flutter and Python."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Networking & API
  http: ^1.2.0

  # File Management
  file_picker: ^8.0.0
  
  # UI & Design
  google_fonts: ^6.2.0
  iconly: ^1.0.1
  cupertino_icons: ^1.0.6

  # Data & Utilities
  shared_preferences: ^2.2.2
  # CORREZIONE QUI SOTTO: Aggiornato alla versione richiesta dall'SDK
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/QUIZAI_logo.png" # <--- CONTROLLA CHE IL NOME SIA ESATTO
  android: true
  ios: true
  windows:
    generate: true
    icon_size: 256